### PR TITLE
get_event_triggers event_xml default value

### PR DESCRIPTION
**Pull request by alexxxxey**

### CODE REVIEW

**Comment by alexxxxey** [comment]
Workaround. self.hik_request.timeout didn't work :(

**Comment by mezz64** [comment]
Thanks for pointing this out, I didn't realize you can't set global timeouts on sessions.

Since we use both get and put, i'm wondering if this style of solution (https://github.com/requests/requests/issues/3341) where we override the HTTPAdapter would be the better fix?

**Comment by mezz64** [comment]
In order to allow the specifying of the connect and read timeouts on the stream object I ended up adding the timeout parameter to each call based on two new constants.  Thanks again for pointing this out, I believe it was likely the culprit in a lot of the reconnect issues that have been around for a while.

**Comment by alexxxxey** [comment]
Thank you!

**Pull request closed without merging**
